name: 'Refresh Submission'
description: 'Refresh Submission on CKB platform'
inputs:
  battle_id:
    description: 'Battle ID'
    required: true
  team_token:
    description: 'TEAM_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - id: login
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://codekatabattle.fly.dev/api/v1/auth/team/login'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"team_token": "${{ inputs.team_token }}"}'
    - uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://codekatabattle.fly.dev/api/v1/battles/${{ inputs.battle_id }}/team/refresh'
        method: 'POST'
        bearerToken: ${{ steps.login.outputs.access_token }}
        data: >
          {
            "github_token": "${{ secrets.GITHUB_TOKEN }}"
            "owner": "${{ github.repository_owner }}"
            "repo": "${{ github.repository }}"
          }
